
@startuml dataFlowDiagram

   
      
    interface start #Black
    agent au as "Audio"

    card HMU as "HMU - Headset Measurement Unit" #aliceblue;line:blue;line.dotted;text:blue {
        agent recau as "Audio recording"
        package HMUPackage as "Digital audio file\nHMU ID\nTime stamp" 
        agent hmupacktrans as "HMU package transmission"
    }

    card PU as "PU - Processsing Unit" #aliceblue;line:blue;line.dotted;text:blue {
        agent hmupackrece as "HMU package recieved"
        agent auproc as "Audio processing" 
        agent noisemes as "Noise calculation"
        agent acshokdet as "Acoustic shock detection"
        package PUpackage as "Noise Data\nShock Data\nHMU ID\nTime stamp"
    }

    database DB as "
        PU package's (HMU ID = 1)
        ----
        PU package's (HMU ID = 2)
        ----
        ...
        ----
        PU package's (HMU ID = n)
        ====
        User ID 1 (HMU ID = 9)
        ----
        User ID 2, (NoHeadset)
        ----
        User ID 3, (HMU ID = 2)
        ---
        ...
        ---
        User ID n, (HMU ID = x)
        " 
    card DU as "DU - Display Unit" #aliceblue;line:blue;line.dotted;text:blue {
        agent recPUpack as "Recevie HMU ID belonging to a User ID\n and latest package's with that HMU ID"
        agent displayData as "display noise and acousticshock data"
            agent enableUser as "Link User ID with HMU ID"

    }
    interface end #white

    start -> au
    au -> recau
    recau -> HMUPackage
    HMUPackage -> hmupacktrans
    hmupacktrans --> hmupackrece
    auproc <- hmupackrece
    noisemes <- auproc
    acshokdet <- noisemes  
    PUpackage <- acshokdet
    PUpackage --> DB 
    DB -> recPUpack
    DB <-- enableUser
    recPUpack -> displayData
    displayData -> end



    
@enduml
