@startuml sequence_diagram_e2e

actor NoiseExposureInvestigator as nei
participant MeasurementUnit as mu
participant DisplayUnit as du
database Database as db
actor HeadsetUser as hu

nei ->> du : Turns on
ref over nei, du : UC2: Turn on Display Unit

hu ->> mu : Turns on
ref over hu, mu : UC1: Turn on Measurement Unit

loop every 1 min

== Display from Measurement Unit == 
    mu -> nei : Print raw MeasurementPackage
    note left
    MuID: n
    Accoustic shocks: m
    Hours left: x
    end note

== Display from Database == 
    du -> db : Request MeasurementPackages
    activate du
    activate db
    db --> du : MeasurementPackages
    deactivate db

    du -> nei : Present measurement data
    deactivate du

    note left
    Hours left: x (default)
    end note

    alt change of measurementPackage info
        nei -> du : Press GUI buttons
        activate du

        note right
        **Button for each parameter:**
        * MuID: n
        * Acoustic shocks: m
        * Hours left: x (default)
        * Timestamp
        end note

        du --> nei : Changed presented measurement data
        deactivate du
    end
end

@enduml