@startuml sequence_diagram_e2e
!pragma teoz true

actor NoiseExposureInvestigator as nei
participant DisplayUnit as du
database Database as db
participant MeasurementUnit as mu
actor HeadsetUser as hu

nei ->> du : Turn on
ref over nei, du : UC2: Turn on Display Unit

{start} hu ->> mu : Turn on
ref over hu, mu : UC1: Turn on Measurement Unit

ref over nei, du, db : UC3: Interact with Display Unit

{end} hu ->> mu : Turn off

{start} <-> {end} : End working day
note left
Working day
aproximated as
8 hours
end note

@enduml