@startuml UC2 : Turn on Display Unit
actor NoiseExposureInvestigator as nei
participant DisplayUnit as du
participant Database as db

nei ->> du : Powers on
activate du

du -> du : Booting...
du --> nei : Screen lighting up
deactivate du

du -> db : Fetch measured data
activate du
activate db

alt Internetconnection fail

db --> du : connection error
du --> nei : "Couldn't connect to server"

else Internetconnection ok

loop every 1 min

db --> du : data
deactivate db

du -> nei : Present measurement data
deactivate du

note left
    **Today** (default):
    * Acoustic shocks
    * Hours left
end note

end
end
@enduml