
@startuml DataFlowDiagram_V2      
    interface start #Black
    agent au as "Audio"

    card MU as "MU - Measurement Unit" #aliceblue;line:blue;line.dotted;text:blue {
        agent InnerRecau as "Inner audio recording"
        agent OuterRecau as "Outer audio recording"
        agent auproc as "Audio processing" 
        agent noisemes as "Noise calculation"
        agent acshokdet as "Acoustic shock detection"
        package MeasurementPackage as "Noise Data\nShock Data\nMU ID\nTime stamp"
    }

    interface end #white

    card DU as "DU - Display Unit" #aliceblue;line:blue;line.dotted;text:blue {
        agent displayData as "display noise and acousticshock data"
        agent recPUpack as "Recevie MU ID belonging to a User ID\n and latest package's with that MU ID"
        agent enableUser as "Link User ID with MU ID"
        
    }
   

    database DB as "
        MeasurementPackages (MU ID = 1)
        ----
        MeasurementPackages (MU ID = 2)
        ----
        ...
        ----
        MeasurementPackages (MU ID = n)
        ====
        User ID 1 (MU ID = 9)
        ----
        User ID 2, (NoHeadset)
        ----
        User ID 3, (MU ID = 2)
        ---
        ...
        ---
        User ID n, (MU ID = x)
        " 
    

    start -> au
    au -> OuterRecau
    au --> InnerRecau
    OuterRecau --> auproc
    InnerRecau -> auproc
    auproc -> noisemes
    noisemes -> acshokdet   
    acshokdet -> MeasurementPackage 
    displayData --> end 
    
    displayData <- recPUpack
    recPUpack -[#aliceblue]> enableUser
    DB --> recPUpack
    DB <-- enableUser
    MeasurementPackage --> DB

@enduml
